### PR TITLE
Remove uses of metriks and its dependencies.

### PR DESCRIPTION
**Pull request by sistawendy**
The `atomic` gem, which is a dependency of `metriks`, has started breaking builds in Ruby 2.4.1. This pull request removes the only use of `metriks` and its dependencies in this repo, which is an optional middleware.

### CODE REVIEW

**Comment by phil-hildebrand** [comment]
Actually, I think there will need to be some changes if metriks is removed.

When a job runs, it appears to call [around_perform](https://github.com/seomoz/qless/blob/0616a5d3acd7efddf2a290a9634324143ab8d510/lib/qless/worker/base.rb#L114) which currently [expects Metriks](https://github.com/seomoz/qless/blob/0616a5d3acd7efddf2a290a9634324143ab8d510/lib/qless/middleware/metriks.rb#L11)

**Comment by phil-hildebrand** [comment]
Maybe you could just take out the require and stub the [metriks functions]]]}(https://github.com/seomoz/qless/blob/master/lib/qless/middleware/metriks.rb) so that middleware still works, it just doen't time the jobs?

**Comment by phil-hildebrand** [comment]
@b4hand / @danlecocq  would either of you be available to weigh in and/or make suggestions?

**Comment by sistawendy** [comment]
If you don't tell Rack to use the middleware, as Barbosa doesn't, the middleware never gets called. Neutering the middleware is an option. Did I mention that we have this branch deployed to production right now?

The tests, by the way, are a disaster.

**Comment by phil-hildebrand** [comment]
Yeah - that make sense.   I do think for those that may use it (middle ware) outside of moz, it might make sense just to stub it out so that if they happen not to have the version pinned, it doesn't blow up.   

I hadn't tried to run the tests yet, so if there are a bunch failing already, I'd agree barbosa in prod is a valid test case 👍

**Comment by sistawendy** [comment]
Hollowed-out metriks middleware added.

**Pull request merged**
